apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: koryalbert-net-pvc
  namespace: koryalbert-net
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
  storageClassName: local-path