apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-local-pvc
  namespace: jelly
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path