apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-data-pvc
  namespace: arr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 3Gi