apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ispyagentdvr-config-pvc
  namespace: dvr
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi